# Generated by Django 5.1.1 on 2024-10-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaama', '0002_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Image')),
            ],
        ),
    ]
